name: Planemo Tool Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'  # Enable dependency caching

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install planemo
        # Uncomment if your tools require these:
        # pip install biopython pandas

    - name: Verify directory structure
      run: |
        echo "Repository contents:"
        ls -lR
        echo "Checking tool directories:"
        [ -d fastp-bracken ] || exit 1
        [ -d mlst-amrfinder-staramr ] || exit 1
        [ -d quast ] || exit 1

    - name: Lint tools
      run: |
        planemo lint fastp-bracken/quality_script_fastp_bracken.xml
        planemo lint mlst-amrfinder-staramr/mlst_amrfinder_staramr.xml
        planemo lint quast/quast_get_fasta.xml

    - name: Run FastP-Bracken tests
      run: |
        planemo test \
          --galaxy_python_version 3.10 \
          --no_container \
          --retries 1 \
          --test_output_all \
          fastp-bracken/quality_script_fastp_bracken.xml

    - name: Run MLST-AMRFinder-StarAMR tests
      run: |
        planemo test \
          --galaxy_python_version 3.10 \
          --no_container \
          --retries 1 \
          --test_output_all \
          mlst-amrfinder-staramr/mlst_amrfinder_staramr.xml

    - name: Run QUAST tests
      run: |
        planemo test \
          --galaxy_python_version 3.10 \
          --no_container \
          --retries 1 \
          --test_output_all \
          quast/quast_get_fasta.xml

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: planemo-test-reports
        path: |
          tool_test_output.html
          */tool_test_output.json
