name: Planemo Tool Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: [
          "fastp-bracken/quality_script_fastp_bracken.xml",
          "mlst-amrfinder-staramr/mlst_amrfinder_staramr.xml",
          "quast/quast_get_fasta.xml"
        ]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Planemo
      run: |
        python -m pip install --upgrade pip
        pip install planemo

    - name: Verify tool XML exists
      run: |
        if [ ! -f "${{ matrix.tool }}" ]; then
          echo "::error::Tool file ${{ matrix.tool }} not found!"
          exit 1
        fi

    - name: Run Planemo tests
      run: |
        planemo test \
          --galaxy_python_version 3.10 \
          --conda_install \
          --conda_ensure_channels conda-forge,bioconda,defaults \
          --retries 1 \
          --test_output_all \
          --no_cache_galaxy \
          --job_config_file job_conf.yml \
          ${{ matrix.tool }}

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: planemo-test-reports-${{ matrix.tool }}
        path: |
          tool_test_output.html
          */tool_test_output.json
